language: rust
dist: xenial
services:
  - xvfb

rust:
  - stable
  - nightly
os:
  - linux
  - osx
  - windows

cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script: cargo test -- --nocapture
