language: rust
dist: xenial
services:
  - xvfb

rust:
  - stable
  - nightly
os:
  - linux
  - osx
  - windows

cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

install:
  -   sudo apt-key update
  -   sudo apt-get -yq update
  -   sudo apt -yq install xvfb gnome-shell

before_script:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sleep 3 # give xvfb some time to start
  - sudo gnome-shell &
  - sleep 3 # give gnome-shell some time to start

script:
  - cargo test -- --nocapture
  - gio trash --help
  - ls
